const a = 4;
const b = 2;
console.log("a: ", a);
console.log("b: ", b);
const c = a - b;
console.log("c: ", c);
const d = a + b;
console.log("d: ", d);
const e = a / b;
console.log("e: ", e);
const f = a * b;
console.log("f: ", f);
