const a = "I'm a string";
console.log("a: ", typeof "I'm a string");
const b = false;
console.log("f: ", typeof false);
const c = true;
console.log("g: ", typeof true);
const d = null;
console.log("h: ", typeof null);
const e = undefined;
console.log("i: ", typeof i);
const j = Symbol("I'm a Symbol");
console.log("j: ", typeof j);
const k = { name: "John" };
console.log("k: ", typeof k);
const l = [1, 2, 3, 4];
console.log("l: ", typeof l);
const m = function run() {
  return 17;
};
console.log("m: ", typeof m);
